DELETE from CLIENT;
INSERT into CLIENT (ID,NAME, SURNAME, PHONE, AGE, EMAIL) VALUES (1,'Thomas','Jefferson','+380504445551','65','testJimmy@gamil.com');
INSERT into CLIENT (ID,NAME, SURNAME, PHONE, AGE, EMAIL) VALUES (2,'Jimmy','Carter','+380974445551','45','testJimmy@gamil.com');
INSERT into CLIENT (ID,NAME, SURNAME, PHONE, AGE, EMAIL) VALUES (3,'Bill','Clinton','+380971111555','50','testBill@gamil.com');

DELETE from PRODUCT;
INSERT into PRODUCT(ID,NAME, PRICE) VALUES (1,'Cocaine 10 gm.',500);
INSERT into PRODUCT(ID,NAME, PRICE) VALUES (2,'Chocolate',10);
INSERT into PRODUCT(ID,NAME, PRICE) VALUES (3,'Moonshine 750 ml',100);
INSERT into PRODUCT(ID,NAME, PRICE) VALUES (4,'Herring 150 ml',10);
INSERT into PRODUCT(ID,NAME, PRICE) VALUES (5,'Bread (loaf)',10);

DELETE from ORDER_PRODUCTS;
DELETE from MAIN_ORDER;

insert into MAIN_ORDER(ID,CLIENT_ID,TOTAL_PRICE) values (1,1,600);
insert into ORDER_PRODUCTS(ID_PRODUCT, ID_ORDER) VALUES (1,1);
insert into ORDER_PRODUCTS(ID_PRODUCT, ID_ORDER) VALUES (3,1);

insert into MAIN_ORDER(ID,CLIENT_ID,TOTAL_PRICE) values (2,3,120);
insert into ORDER_PRODUCTS(ID_PRODUCT, ID_ORDER) VALUES (3,2);
insert into ORDER_PRODUCTS(ID_PRODUCT, ID_ORDER) VALUES (4,2);
insert into ORDER_PRODUCTS(ID_PRODUCT, ID_ORDER) VALUES (5,2);

